FROM node:22-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ARG VITE_API_URL
ARG VITE_AUTH_URL
ARG VITE_AUTH_CLIENT_ID
ARG VITE_CORUJAO_API_URL
ARG VITE_MIX_API_URL
ARG VITE_ALLOWED_HOSTS
ARG VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS

RUN VITE_API_URL=$VITE_API_URL \
    VITE_AUTH_URL=$VITE_AUTH_URL \
    VITE_AUTH_CLIENT_ID=$VITE_AUTH_CLIENT_ID \
    VITE_CORUJAO_API_URL=$VITE_CORUJAO_API_URL \
    VITE_MIX_API_URL=$VITE_MIX_API_URL \
    VITE_ALLOWED_HOSTS=$VITE_ALLOWED_HOSTS \
    VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=$VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS \
    npm run build

FROM nginx:1.27-alpine AS runner

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 3000
